## Build libuv
FROM debian:stretch-slim as uv-build
WORKDIR /source
RUN apt update && apt upgrade -y && apt install -y git curl python lsb-release sudo g++ wget make
RUN wget "https://github.com/libuv/libuv/archive/v1.30.1.tar.gz" \
    && tar -zxvf v1.30.1.tar.gz \
    && mv libuv-1.30.1 uv
RUN cd uv \
    && git clone https://chromium.googlesource.com/external/gyp build/gyp
RUN cd uv \
    && ./gyp_uv.py -f make \
    && BUILDTYPE=Release make -C out
CMD ["/bin/sh"]