const { File, O_RDONLY, O_WRONLY, O_RDWR, O_APPEND, O_CREAT, O_TRUNC, O_EXCL } = module('fs', {})
const buf = Buffer.alloc(4096)
const fs = new File()
let r = fs.setup(buf, buf)
print(`setup: ${r}`)
const fd = fs.open('./foo.txt', O_RDWR | O_CREAT)
print(`open: ${fd}`)
r = fs.read(5)
if (r > 0) print(buf.read(0, 5))
print(`read: ${r}`)
r = fs.write(buf.write('omg, this is so cool!'), 0)
print(`write: ${r}`)
r = fs.close()
print(`close: ${r}`)
